services:
  bot:
    image: 4lch4/shion-bot:${SHION_TAG:-0.0}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${API_PORT:-3000}:${API_PORT:-3000}"
    init: true
    restart: unless-stopped

  register-commands:
    image: 4lch4/shion-bot:${SHION_TAG:-0.0}
    build:
      context: .
      dockerfile: Dockerfile
    command: ["bun", "run", "src/deploy-commands.ts"]
    env_file:
      - .env
    init: true
    profiles:
      - setup
    restart: "no"
